# Generated by Django 5.1.2 on 2024-11-25 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='igrac',
            table='Igrac',
        ),
        migrations.AlterModelTable(
            name='natjecanje',
            table='Natjecanje',
        ),
        migrations.AlterModelTable(
            name='tim',
            table='Tim',
        ),
        migrations.AlterModelTable(
            name='utakmica',
            table='Utakmica',
        ),
    ]
