# Generated by Django 5.1.2 on 2024-11-25 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_igrac_table_alter_natjecanje_table_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='igrac',
            options={'verbose_name': 'Igrac', 'verbose_name_plural': 'Igraci'},
        ),
        migrations.AlterModelOptions(
            name='natjecanje',
            options={'verbose_name': 'Natjecanje', 'verbose_name_plural': 'Natjecanja'},
        ),
        migrations.AlterModelOptions(
            name='tim',
            options={'verbose_name': 'Tim', 'verbose_name_plural': 'Timovi'},
        ),
        migrations.AlterModelOptions(
            name='utakmica',
            options={'verbose_name': 'Utakmica', 'verbose_name_plural': 'Utakmice'},
        ),
        migrations.AlterModelTable(
            name='igrac',
            table='igrac',
        ),
        migrations.AlterModelTable(
            name='natjecanje',
            table='natjecanje',
        ),
        migrations.AlterModelTable(
            name='tim',
            table='tim',
        ),
        migrations.AlterModelTable(
            name='utakmica',
            table='utakmica',
        ),
    ]
